.PHONY: setup build lint test

setup:
	python3 -m venv .venv \
	&& source .venv/bin/activate \
	&& pip3 install -r requirements.txt

build:
	pip3 install -r requirements.txt

lint:
	echo "Not implemented"

fmt:
	echo "Not implemented"

test:
	echo "Not implemented"
